export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const GENERATE_ASSET_RANDOM_INDEX = 'GENERATE_ASSET_RANDOM_INDEX';

export const START_DRAGGING_TAB = 'START_DRAGGING_TAB';
export const STOP_DRAGGING_TAB = 'STOP_DRAGGING_TAB';

export const PLAY_MUSIC = 'PLAY_MUSIC';
export const CLEAR_MUSIC = 'CLEAR_MUSIC';

export const PLAY_SOUND = 'PLAY_SOUND';
export const CLEAR_SOUND = 'CLEAR_SOUND';
